### ISSUE TITLE
Nonexistant lua folder

### ISSUE THREAD

**Issue by Hitechcomputergeek** [MikuAuahDark/HonokaMiku#1]
I quote from the readme:

> Lua implementation of EN & JP decryption routines located in `lua` folder.

However, there is no such `lua` folder anywhere to be found.

Might want to fix that.

**Comment by MikuAuahDark** [comment]
I deleted the Lua implementation some time ago because I think no one will need it. However, if you really want it, I'll write the Lua version for you.

See commit 1f05ff25968de86d87e79842d2333a3e42d6b25b

**Comment by Hitechcomputergeek** [comment]
I don't. IMO it's rather a waste of your time to port this to three different programming languages. I'd rather you spend time improving the regular C++ version.

**Comment by MikuAuahDark** [comment]
Well, of course the C++ version is always better because it compiled to native code.

Okay, looks like I can close this.

**Comment by Hitechcomputergeek** [comment]
That's not quite true. There are advantages to both interpreted and compiled languages. Both of them are neither better nor worse than the other one.

I just mentioned the C++ version because AFAIK it was the first one you wrote.

**Comment by MikuAuahDark** [comment]
Not really. Actually, I wrote it in Lua first, then I translate it to C++.
28 Mar 2016 08.41, "Hitechcomputergeek" notifications@github.com menulis:
