### ISSUE TITLE
Cannot decrypt: Cannot find suitable decryption method

### ISSUE THREAD

**Issue by Hitechcomputergeek** [MikuAuahDark/HonokaMiku#2]
After compiling on Ubuntu 15.10, for any file I try to decrypt (from the built-in assets included in the app), I get the following error:

```
htcg@htcg-tp11e ~/Documents/klab $ HonokaMiku start.lua 
HonokaMiku. Universal LL!SIF game files decrypter
Auto detecting: Unknown
Cannot decrypt start.lua: Cannot find suitable decryption method
```

I have tried decrypting assets from the iOS EN version (you can't get the JP version without a Japanese Apple ID - thanks, Apple), the Android EN version, and the Android JP version of the game.

Here's the start.lua file from the iOS version of the app: [link](https://drive.google.com/uc?id=0B6uUaliqVM7CTFFNQXdPTG5EYWs) ([mirror](http://htcg.ddns.net/f/SIF/start.lua))

**Comment by MikuAuahDark** [comment]
It's working fine under Windows (start.lua is come from your link).

```
C:\Users\MikuAuahDark>HonokaMiku -d start.lua
HonokaMiku. Universal LL!SIF game files decrypter
Detecting: EN game file
```

Please show me the output of `HonokaMiku -v`

**Comment by Hitechcomputergeek** [comment]
```
HonokaMiku. Universal LL!SIF game files decrypter
Version 2.3.1
Build at Mar 30 2016 17:24:24
Compiled using gcc-5.2.1 20151010
```

For the heck of it, I built it with Clang, that doesn't work either:

```
HonokaMiku. Universal LL!SIF game files decrypter
Version 2.3.1
Build at Apr  1 2016 14:18:58
Compiled using 4.2.1 Compatible Ubuntu Clang 3.6.2 (tags/RELEASE_362/final)
```

**Comment by MikuAuahDark** [comment]
I'll boot to Ubuntu and do some test after I'm in home. I'm in the school
right now.

EDIT: Ok looks like there's issue in Ubuntu. I'll see if I can fix them.

**Comment by MikuAuahDark** [comment]
Ok I got it fixed. You can try to recompile it now.
