### ISSUE TITLE
Compiling on Mac

### ISSUE THREAD

**Issue by xfoxfu** [MikuAuahDark/HonokaMiku#3]
I am an OS X user. The default Makefile doesn't works as OS X  offers Clang as `g++` command.

I would suggest change the `g++` commands to `$(CC)`.

Besides, what are the compiler options `-Wl,-E` used for? If I remove it, the compiling succeeds, but if not, the compiler says:

```
mkdir -p bin/honokamiku
g++-4.8 -O3  -fPIC -pie -o bin/honokamiku/HonokaMiku   JP_Decrypter.o V2_Decrypter.o Helper.o HonokaMiku.o  -Wl,-E
ld: unknown option: -E
collect2: error: ld returned 1 exit status
make: *** [honokamiku] Error 1
```

**Comment by MikuAuahDark** [comment]
actually compiling HonokaMiku can be done with single command line. Execute
this command in HonokaMiku directory.

g++ -o HonokaMiku src/*.cc
21 Mei 2016 11.18, "小傅Fox" notifications@github.com menulis:
